import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Link from "next/link";
import ThemeProvider from "./providers/ThemeProvider";
import Navbar from "./components/Navbar";
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={"montserrat.className"}>
        <ThemeProvider>
          <Navbar />
          <Link href="/">Home</Link>
          <Link href="/dashboard/">Dashboard</Link>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
